
packages:
  - workflow
  - model
  - ui
  - test
  - block

catalog:
  "@platforma-sdk/model": ^1.22.18
  "@platforma-sdk/ui-vue": ^1.22.39
  "@platforma-sdk/workflow-tengo": ^2.12.1
  "@platforma-sdk/block-tools": ^2.5.13
  "@platforma-sdk/test": ^1.22.49
  "@platforma-sdk/tengo-builder": ^1.17.7
  "@platforma-sdk/package-builder": ^2.15.4
  "@milaboratories/graph-maker": ^1.1.45

  "@platforma-open/milaboratories.runenv-python-3": ^1.1.7
  "@platforma-open/milaboratories.software-small-binaries": ^1.15.6
  "@platforma-open/milaboratories.software-mixcr": 4.7.0-139-develop
  
  "vue": ^3.5.13
  "vue-tsc": ^2.2.0
  
  "typescript": ^5.7.3
  "tsup": ~8.3.6
  "turbo": ^2.4.4

  "vite": ^6.0.11
  "vitest": ^3.0.5
  "@vitejs/plugin-vue": ^5.2.1

  "@changesets/cli": ^2.28.0
