
packages:
  - workflow
  - model
  - ui
  - test
  - block

catalog:
  "@platforma-sdk/model": ^1.34.8
  "@platforma-sdk/ui-vue": ^1.34.8
  "@platforma-sdk/workflow-tengo": ^4.8.0
  "@platforma-sdk/block-tools": ^2.5.55
  "@platforma-sdk/test": ^1.34.8
  "@platforma-sdk/tengo-builder": ^2.1.10
  "@platforma-sdk/package-builder": ^2.15.4

  "@platforma-open/milaboratories.runenv-python-3": ^1.1.16
  "@platforma-open/milaboratories.software-mixcr": 4.7.0-139-develop
  
  "vue": ^3.5.13
  "vue-tsc": ^2.2.10
  
  "typescript": ~5.5.4
  "tsup": ~8.3.6
  "turbo": ^2.5.2

  "vite": ^6.3.3
  'vitest': ~2.1.8
  "@vitejs/plugin-vue": ^5.2.3

  "@changesets/cli": ^2.29.2
